title: Junyuan Li's Homepage
page-top-title: Junyuan Li
sidebar-name: Junyuan Li (李浚源)
sidebar-affiliation: Shandong University of Finance and Economics (SDUFE)
sidebar-location: Jinan, Shandong, China
sidebar-email: Email
sidebar-email-link: mailto:18660815708@163.com
sidebar-github: GitHub
sidebar-github-link: https://github.com/Junyuan-Li
sidebar-scholar: Google Scholar
sidebar-scholar-link: '#'
sidebar-orcid: ORCID
sidebar-orcid-link: '#'
sidebar-rg: ResearchGate
sidebar-rg-link: '#'
copyright-text: © Junyuan Li 2026. All Rights Reserved.
